### ISSUE TITLE
Mute_GunShotsMode not working consistently

### ISSUE THREAD

**Issue by M-archand** [oqyh/cs2-Game-Manager-GoldKingZ#6]
With `Mute_GunShotsMode = 1` I am hearing all gun shots as the person shooting (not sure if that's intended or not). As a separate player I hear gun shots inconsistently depending on where I'm standing relative to the person shooting. Also, when you can hear them they're much softer compared to the regular sound, but not fully muted. I've attached a video with an example.

https://github.com/user-attachments/assets/c14d6fc9-512b-4e52-b5b6-080ebe3f94ab

**Comment by oqyh** [comment]
> With `Mute_GunShotsMode = 1` I am hearing all gun shots as the person shooting (not sure if that's intended or not). As a separate player I hear gun shots inconsistently depending on where I'm standing relative to the person shooting. Also, when you can hear them they're much softer compared to the regular sound, but not fully muted. I've attached a video with an example.
> 
>  Mute_GunShotsMode.mp4

that's how it intended

**Comment by M-archand** [comment]
@oqyh  Why close the issue? If it's intended for the person shooting to still hear sounds that is fine. But why am I still hearing shooting as the person being shot at?

**Comment by oqyh** [comment]
> @oqyh Why close the issue? If it's intended for the person shooting to still hear sounds that is fine. But why am I still hearing shooting as the person being shot at?

bullet it self not muted 
the gunshot from weapon it self only
